### ISSUE TITLE
Turn relais OFF on Octoprint shutdown not not working

### ISSUE THREAD

**Issue by hobbes68** [da4id/OctoPrint-MyStromSwitch#17]
Hello,
I try to use your command Turn relais OFF on Octoprint shutdown but the shutdown system command  (sudo shutdown -h now) in octoprint didn't start the countdown in Mystrom Wifiswitch 3.82.
But the resart Octoprint command (sudo service octoprint restart) start the countdown (60sec in my case). So the power supply of the raspi is switch off without shutdown!
I hope it's clear enough.
Did I something wrong?
Best regards

**Comment by da4id** [comment]
Hi
Thanks for reporting this bug. I faced the same issue on my Octopi installation yesterday night. Ive testet this feature only on an octoprint installation on my computer.
Ive checked the logs of the Octoprint 
`2019-12-16 22:15:34,819 - octoprint.plugins.automaticshutdown - INFO - Shutting down system with command: sudo shutdown -h now
2019-12-16 22:15:35,318 - octoprint.server - INFO - Shutting down...
2019-12-16 22:15:35,829 - octoprint.events - INFO - Processing shutdown event, this will be our last event
2019-12-16 22:15:36,128 - octoprint.events - INFO - Event loop shut down
2019-12-16 22:15:36,136 - octoprint.plugin - ERROR - Error while calling plugin hardwarepwm
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/plugin/__init__.py", line 219, in call_plugin
    result = getattr(plugin, method)(*args, **kwargs)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_hardwarepwm/__init__.py", line 51, in on_shutdown
    self.stopPWM(self.IOpin);
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_hardwarepwm/__init__.py", line 32, in stopPWM
    self.GPIO.write(pin, 0)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/pigpio.py", line 1429, in write
    return _u2i(_pigpio_command(self.sl, _PI_CMD_WRITE, gpio, level))
  File "/home/pi/oprint/local/lib/python2.7/site-packages/pigpio.py", line 994, in _pigpio_command
    dummy, res = struct.unpack('12sI', sl.s.recv(_SOCK_CMD_LEN))
error: unpack requires a string argument of length 16
2019-12-16 22:15:36,137 - octoprint.plugins.mystromswitch - INFO - Turn off Relais on Shutdown Delayed
2019-12-16 22:15:36,147 - octoprint.plugins.mystromswitch - INFO - Error during powerCycle Relais
2019-12-16 22:15:36,158 - octoprint.plugins.mystromswitch - INFO - Error during powerCycle Relais
2019-12-16 22:15:36,170 - octoprint.plugins.mystromswitch - INFO - Error during powerCycle Relais
2019-12-16 22:15:36,171 - octoprint.server - INFO - Goodbye!
`

It seems that the Powercycle command was issued by the plugin, but the command get lost somewhere.

**Comment by kirtapatrik** [comment]
Same problem here.
OctoPrint 1.3.12 auf OctoPi 0.17.0 on Raspberry Pi 4

**Comment by da4id** [comment]
It seems that the network connection is shutted down before the Plugin gets the on shutdown event. Therefore it cannot send the command to the Switch. 
If you shut down your System over the Websurface -> Shutdown System it works. If you use automatic shutdown Plugin it wont work. 

I will try to change the shutdown order of the services

**Comment by da4id** [comment]
The quick fix is to change the following line in the `/etc/init.d/octoprint` file on your raspberry pi 
[difference](https://github.com/da4id/OctoPi/commit/33217ff0b1a40e3ed656abb6b8276202e0a1f118)
The file should then look like
[whole file](https://github.com/da4id/OctoPi/blob/33217ff0b1a40e3ed656abb6b8276202e0a1f118/src/modules/octopi/filesystem/root/etc/init.d/octoprint#L6)

I started a Pull Request that this change is default on Octopi

**Comment by hobbes68** [comment]
Hello i spend 3 hours to change this scrips file! Finaly it's working. I'm
not used for programing... My notepad++ plugin was not uptodate for
connecting my pi, i had to change the permission for the scrip file,
install the desktop on my octopi... I learned so much this evening! Thanks
a lot and happy Christmas

**Comment by da4id** [comment]
Change is now available in the official OctoPi image. At the moment there is no new release available. But you can use [Nigthly Builds](https://gnethomelinux.com/OctoPi/nightly/) instead. These are not tested, but have all new features and improvements enabled. When you do this please Backup your SD Card bevore updating. You also need to export and import all Octoprint settings.

If you wont use Nightly Builds you can change the file manually. The easiest way is to log in to your OctoPi over ssh (Google ssh Raspberry Pi, default login user: pi, password: raspberry). Then type `sudo nano /etc/init.d/octoprint`. Then use Cursor arrows to navigate to the corresponding line and change it. Press `CTRL + o` followed by `Enter` and then `CTRL + x`

I'm closing this Issue now

**Comment by kirtapatrik** [comment]
Is it possible that this fix has no effect on a Raspberry Pi 4?

With the plugin AutomaticShutdown, the switch is not switched off after the print is finished.
When I shutdown my system via the websurface -> "Shutdown System", it does not work either.

When I press the button on the web interface, the switch switches without any problems.

**Comment by hobbes68** [comment]
Hello,
It doesn’t work for me anymore with the shutdown system… or just « sometimes » it’s works, but usually not.
Best regards

**Comment by da4id** [comment]
Hi thanks for feedback

I need some more time to find the problem. I improved the logging of the Plugin. 
the command to turn off the switch fails with this error Message. It seems that the networking dependency is not always working.
`ERROR - HTTPConnectionPool(host='192.168.1.52', port=80): Max retries exceeded with url: /timer?mode=on&time=60 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x67611d10>: Failed to establish a new connection: [Errno 101] Network is unreachable',))`

**Comment by da4id** [comment]
I have added a new feature in #21 to make it work
Use these settings
![Bildschirmfoto vom 2020-06-28 17-13-44](https://user-images.githubusercontent.com/20624741/85951348-e9e11f80-b962-11ea-8363-dc0d34032e40.png)

and dont forget to enable it!
![Bildschirmfoto vom 2020-06-28 17-14-04](https://user-images.githubusercontent.com/20624741/85951357-fb2a2c00-b962-11ea-89e9-503dd7f7fb1f.png)
