### ISSUE TITLE
Button taucht nicht auf

### ISSUE THREAD

**Issue by DunklerPhoenix** [da4id/OctoPrint-MyStromSwitch#22]
Heho. 
Vielen Dank für dein Plugin. Ich habe aktuell das Problem, dass der Button nach der Konfiguration nicht auftaucht.
Was kann ich da tun?
![chrome_xv4OmojChS](https://user-images.githubusercontent.com/1261305/75569057-acbc5d80-5a54-11ea-8bc7-2bcc05465439.png)
![chrome_fe49iT6Ioe](https://user-images.githubusercontent.com/1261305/75569059-ad54f400-5a54-11ea-9e75-08749f78b483.png)
![chrome_AludQlHH44](https://user-images.githubusercontent.com/1261305/75569060-aded8a80-5a54-11ea-88e4-fa025fb72a49.png)

EDIT:

Es wird folgende Meldung im Log geworfen:
`2020-02-28 18:32:18,240 - octoprint.plugins.mystromswitch - ERROR - HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //192.168.1.200/report (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71475db0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_mystromswitch/__init__.py", line 82, in _timer_task
    'http://{}/report'.format(self.ip), timeout=1)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/raven/breadcrumbs.py", line 341, in send
    resp = real_send(self, request, *args, **kwargs)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)`

**Comment by DunklerPhoenix** [comment]
Ok. Es darf kein http:// angegeben werden in den Einstellungen :D
